language: php
php:
  - 7.1

before_install:
  # Turn off XDebug
  - phpenv config-rm xdebug.ini || return 0

install:
  # Composer
  - travis_retry composer install --no-progress --prefer-dist

script:
  # Coding standard
  - composer run-script cs

cache:
  directories:
    - $HOME/.composer/cache
